app:
  build: '.'
  dockerfile: 'DockerfileDev'
  volumes:
    - '.:/home/app/src'
  environment:
    PORT: 8080
    FORCE_HTTPS: 'false'
    VIRTUAL_HOST: 'healthcheck.*'
    SLACK_HOOK:
    SLACK_CHANNEL:
