maxEntries: 100
interval: 'every 10 seconds'
retryDelay: 1000
verbose: false
ua: 'healthcheck'
slack:
  emoji: '{{ENV.SLACK_EMOJI || ":warning:"}}'
  channel: '{{ENV.SLACK_CHANNEL}}'
  slackHook: '{{ENV.SLACK_HOOK}}'
  slackCommandToken: '{{ENV.SLACK_TOKEN || false}}'
sns:
  enabled: '{{(ENV.SNS_TOPIC) ? true : false}}'
  clientId: '{{ ENV.AWS_ACCESS_KEY_ID }}'
  secretId: '{{ ENV.AWS_SECRET_ACCESS_KEY }}'
  topic: '{{ ENV.SNS_TOPIC }}'
plugins:
  slack-command:
    _enabled: '{{(slack.slackCommandToken) ? true : false}}'
    routeToListen: '/api/command'
    token: '{{slack.slackCommandToken}}'
  './lib/slack':
  hapi-method-loader:
    _priority: -7
  hapi-method-scheduler:
    _priority: -6
    timezone: 'America/Los_Angeles'
    noParamsLength: true
    schedule: []
  vision:
    _priority: -5
  './lib/healthcheck':
    _priority: -4
  './lib/db':
    logPath: '{{ ENV.LOG_PATH }}'
    _priority: -4
  inert:
  hapi-route-loader:
  hapi-logr:
    reporters:
      sns:
        reporter: 'logr-sns'
        options:
          enabled: '{{ sns.enabled }}'
          clientId: '{{ sns.clientId }}'
          secretId: '{{ sns.secretId }}'
          topic: '{{ sns.topic }}'
          throttle: '{{1000 * 60 * 10}}'
          throttleBasedOnTags: true
          filter:
            - 'service-down'
            - 'service-restored'
            - 'certificate-expiration'
      consoleColor:
        options:
          colors:
            'service-down': 'bgRed'
            'service-restored': 'bgGreen'
            'service-slow': 'bgYellow'
      flat:
        options:
          tagColors:
            'service-down': 'bgRed'
            'service-restored': 'bgGreen'
            'service-slow': 'bgYellow'
      slack:
        reporter: 'logr-slack'
        options:
          iconEmoji: '{{slack.emoji}}'
          channel: '{{ENV.SLACK_CHANNEL || undefined}}'
          enabled: '{{(slack.slackHook) ? true : false}}'
          throttle: '{{1000 * 60 * 10}}'
          throttleBasedOnTags: true
          username: 'HealthCheck'
          hideTags: true
          slackHook: '{{slack.slackHook}}'
          tagColors:
            'service-down': 'danger'
            'service-restored': 'good'
            'service-slow': 'warning'
          filter:
            - 'service-down'
            - 'service-restored'
            - 'notice'
            - 'certificate-expiration'
