plugins:
  hapi-method-loader:
    _priority: -6
  vision:
    _priority: -5
  './lib/healthcheck':
    _priority: -5
  inert:
  hapi-route-loader:
  hapi-logr:
    reporters:
      consoleColor:
        options:
          colors:
            'service-down': 'red'
            'service-restored': 'green'
            'service-slow': 'yellow'
      flat:
        options:
          tagColors:
            'service-down': 'red'
            'service-restored': 'green'
            'service-slow': 'yellow'
      slack:
        reporter: 'logr-slack'
        options:
          throttle: 1000 * 60
          throttleBasedOnTags: true
          username: 'HealthCheck'
          hideTags: true
          tagColors:
            'service-down': 'danger'
            'service-restored': 'good'
            'service-slow': 'warning'
          filter:
            - 'service-down'
            - 'service-restored'
            - 'start'
  hapi-method-scheduler:
    schedule: []

ua: 'healthcheck'
