plugins:
  hapi-method-loader:
    _priority: -7
  hapi-method-scheduler:
    _priority: -6
    timezone: 'America/Los_Angeles'
    schedule: []
  vision:
    _priority: -5
  './lib/healthcheck':
    _priority: -4
  inert:
  hapi-route-loader:
  hapi-logr:
    reporters:
      consoleColor:
        options:
          colors:
            'service-down': 'red'
            'service-restored': 'green'
            'service-slow': 'yellow'
      flat:
        options:
          tagColors:
            'service-down': 'red'
            'service-restored': 'green'
            'service-slow': 'yellow'
      slack:
        reporter: 'logr-slack'
        options:
          username: 'HealthCheck'
          hideTags: true
          tagColors:
            'service-down': 'danger'
            'service-restored': 'good'
            'service-slow': 'warning'
          filter:
            - 'service-down'
            - 'service-restored'
            - 'start'

ua: 'healthcheck'
