maxEntries: 100
interval: 'every 10 seconds'
retryDelay: 1000
verbose: false
ua: 'healthcheck'
userAgent: '{{ envVars.userAgent }}'
logPath: '{{envVars.logPath}}'
slack:
  name: '{{envVars.slack.name}}'
  emoji: '{{envVars.slack.emoji}}'
  channel: '{{envVars.slack.channel}}'
  hook: '{{envVars.slack.hook}}'
  enabled: '{{envExists("SLACK_HOOK")}}'
  commandToken: '{{envVars.slack.commandToken}}'
sns:
  region: '{{ envVars.region }}'
  clientId: '{{ envVars.clientId }}'
  secretId: '{{ envVars.secretId }}'
  topic: '{{ envVars.topic }}'
  enabled: '{{envExists("SNS_TOPIC")}}'
