plugins:
  hapi-views:
    dataPath: '{{CWD}}'
    routes:
      '/routes':
        view: 'pages/status'
        data:
          # status: '{request.server.inject('api/all').result.status}'
          status: '/api/all'
