maxEntries: 100
interval: 'every 10 seconds'
retryDelay: 1000
verbose: false
ua: 'healthcheck'
userAgent: '{{getEnv("USER_AGENT", "")}}'
logPath: '{{ENV.LOG_PATH}}'
slack:
  emoji: '{{getEnv("SLACK_EMOJI", ":warning:")}}'
  channel: '{{getEnv("SLACK_CHANNEL", undefined)}}'
  hook: '{{ENV.SLACK_HOOK}}'
  enabled: '{{envExists("SLACK_HOOK")}}'
  commandToken: '{{getEnv("SLACK_TOKEN", false)}}'
sns:
  region: '{{ ENV.AWS_DEFAULT_REGION }}'
  clientId: '{{ ENV.AWS_ACCESS_KEY_ID }}'
  secretId: '{{ ENV.AWS_SECRET_ACCESS_KEY }}'
  topic: '{{ ENV.SNS_TOPIC }}'
  enabled: '{{envExists("SNS_TOPIC")}}'
