maxEntries: 100
interval: 'every 10 seconds'
retryDelay: 1000
verbose: true
ua: 'healthcheck'
logPath: '{{ENV.LOG_PATH}}'
slack:
  emoji: '{{ENV.SLACK_EMOJI || ":warning:"}}'
  channel: '{{ENV.SLACK_CHANNEL || undefined}}'
  hook: '{{ENV.SLACK_HOOK}}'
  commandToken: '{{ENV.SLACK_TOKEN || false}}'
sns:
  enabled: '{{(ENV.SNS_TOPIC) ? true : false}}'
  clientId: '{{ ENV.AWS_ACCESS_KEY_ID }}'
  secretId: '{{ ENV.AWS_SECRET_ACCESS_KEY }}'
  topic: '{{ ENV.SNS_TOPIC }}'
