maxEntries: 100
interval: 'every 30 seconds'
verbose: true
retryDelay: 500
urls:
  -
    name: 'certificate'
    url: 'https://google.com'
    type: ping
    interval: 'every 24 hours'
  -
    name: 'Random'
    url: http://localhost:8080/api/random
    type: http
  -
    name: 'Dev'
    url: localhost
    type: ping
    responseThreshold: 30
